### ISSUE TITLE
Propose to add a .clang-format specification to this project ...

### ISSUE THREAD

**Issue by LuminousXLB** [intel/SGXDataCenterAttestationPrimitives#195]
which will help the community to read the code easier.

Here's my proposal.

```yaml
---
BasedOnStyle: LLVM
IndentWidth: 4
ColumnLimit: 0
---
Language: Cpp
AllowShortIfStatementsOnASingleLine: false
```
